site_name: Nefel Tellioglu
site_description: M.Sc. Industrial Engineering | Boğaziçi University
site_url: https://nefeltellioglu.github.io
repo_url: https://github.com/nefeltellioglu/nefeltellioglu.github.io

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs.link
  palette:
    primary: indigo
    accent: blue
  favicon: assets/images/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - attr_list
  - tables
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_css:
  - assets/css/custom.css

extra_javascript:
  - https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js

nav:
  - Home: index.md
  - About: about.md
  - Publications: papers.md
  - Teaching: teaching.md
  - Contact: contact.md

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:your@email.com
    - icon: fontawesome/brands/github
      link: https://github.com/nefeltellioglu
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yourprofile
    - icon: fontawesome/solid/graduation-cap
      link: https://scholar.google.com/citations?user=YOUR_ID